name: khartes
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - opencv
  - pyqt=5
  - tifffile
  - zarr=3
  - scipy
  - pynrrd
  - rectpack
  - pyopengl
  - requests
  - aiohttp
  - fsspec
  - cmap
